server {
    listen 80;
    server_name power.domain.name;

    location / {
        proxy_pass http://127.0.0.1:8000;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # access_log /var/log/nginx/power.access.log;
    # error_log /var/log/nginx/power.error.log;
}

location /ping {
    allow YOUR_HOME_IP;
    deny all;

    proxy_pass http://127.0.0.1:8000;
}